/*
 *  Copyright 2010 by AMLOGIC INC.
 *
 *  Modem Support List
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; version 2 of the License.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *  
 *  Author:  Frank Chen <frank.chen@amlogic.com>
 */


#ifndef _MODEM_SUPPORT_LIST_H
#define _MODEM_SUPPORT_LIST_H

/*  vid                 pid                                                                                          */
/*  name                                                                                                           */
/*  type                                                                                                             */
/*  modem port        service port         diag port          voice port          gps port     */
/*  networktype                                                                                                  */
/*  service                                                                                                         */

//ZTE MF633, MF637U, MF110                 dongle
{
	0x19d2, 0x0031,
	"ZTE MF637U or MF633 or MF110",
	RIL_MODEM_TYPE_USB_DONGLE,
	"/dev/ttyUSB2", "/dev/ttyUSB1", "/dev/ttyUSB0", NULL,           NULL, "2",  "1" ,
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//ZTE AD3812 & MG3732                  module
{ 
	0x19d2, 0xFFEB, 
	"ZTE AD3812 or MG3732",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB3", "/dev/ttyUSB0", "/dev/ttyUSB2", "/dev/ttyUSB1", NULL, "3", "0" ,
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//ZTE MC8630                                 module
{
	0x19d2, 0xFFFE,
	"ZTE MC8630",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0",	"/dev/ttyUSB1", "/dev/ttyUSB3", "/dev/ttyUSB2", NULL, "0","1" ,
	RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//ZTE MC2700 & MC2716                  module
{
	0x19d2, 0xFFED,
	"ZTE MC2700 or MC2716",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB1", "/dev/ttyUSB3", "/dev/ttyUSB2", NULL, "0", "1" ,
	RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//ZTE MC2718                                 module
{
	0x19d2, 0xFFE8,
	"ZTE MC2718",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB1", "/dev/ttyUSB3", "/dev/ttyUSB2", "/dev/ttyUSB4", "0", "1",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//ZTE MC2816                                 module
{
	0x19d2, 0xFFF1,
	"ZTE MC2816",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB1", "/dev/ttyUSB3", "/dev/ttyUSB2", "/dev/ttyUSB4","0","1",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},	

//ZTE MF210                                    module
{
	0x19d2, 0x0117,
	"ZTE MF210",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB2", "/dev/ttyUSB1", "/dev/ttyUSB0", "/dev/ttyUSB2", "/dev/ttyUSB4","2","1",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},	

//ZTE MF226                                    module
{
	0x19d2, 0x0144,
	"ZTE MF226",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB4", "/dev/ttyUSB2", "/dev/ttyUSB0", "/dev/ttyUSB1", "/dev/ttyUSB3","4","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//ZTE AC580                                    module
{
	0x19d2, 0x0152,
	"ZTE AC580",
	RIL_MODEM_TYPE_USB_DONGLE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL, NULL, NULL,"0","3",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//LONGCHEER U6300/U6100             module
{
	0x1C9E, 0x9603,
	"LONGCHEER U6300 or U6100",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB2", "/dev/ttyUSB1", "/dev/ttyUSB0", NULL,           NULL, "2","1",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},	


//HUAWEI E1820             module
{     
	0x12d1, 0x14ac,    
	"HUAWEI E1820",    
	RIL_MODEM_TYPE_USB_DONGLE,    
	"/dev/ttyUSB0", "/dev/ttyUSB3", NULL, "/dev/ttyUSB1", "/dev/ttyUSB2",    "0","3",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA,    
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
}, 

//Vodafone (Huawei) K3770            module
{     
	0x12d1, 0x14c9,    
	"HUAWEI K3770",    
	RIL_MODEM_TYPE_USB_DONGLE,    
	"/dev/ttyUSB0", "/dev/ttyUSB1", NULL, NULL, NULL,    "0","1",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA,    
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
}, 

//Huawei E1750/E620                      dongle
{
	0x12D1, 0x1001,
	"Huawei E620",
	RIL_MODEM_TYPE_USB_DONGLE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL,    "0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei E220/E160
{
	0x12D1, 0x1003,
	"Huawei E220",
	RIL_MODEM_TYPE_USB_DONGLE,
	"/dev/ttyUSB0", "/dev/ttyUSB1", NULL,           NULL,           NULL,   "0","1",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei?? 
{
	0x12D1, 0x1004,
	"Huawei E1004",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL,  "0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei EM770J
{
	0x12D1, 0x1402,
	"Huawei EM770J",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL,   "0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei EW770W                          module
{
	0x12D1, 0x1404,
	"Huawei EW770W",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           "/dev/ttyUSB3",  "0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei?? 
{
	0x12D1, 0x1406,
	"Huawei E1406",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB1", NULL,           NULL,           NULL,  "0","1",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei?? 
{
	0x12D1, 0x1407,
	"Huawei E1407",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB1", NULL,           NULL,           NULL, "0","1",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei?? 
{
	0x12D1, 0x140A,
	"Huawei E140A",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL,  "0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei?? 
{
	0x12D1, 0x140B,
	"Huawei E140B",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL,  "0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei E173u, EC122
{
	0x12D1, 0x140C,
	"Huawei E173u",
	RIL_MODEM_TYPE_USB_DONGLE,
	"/dev/ttyUSB0", "/dev/ttyUSB3", NULL,           NULL,           NULL,  "0","3",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA |RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x1411,
	"Huawei E1411",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL,  "0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x1412,
	"Huawei E1412",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL, "0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x1413,
	"Huawei E1413",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB3", NULL,           NULL,           NULL, "0","3",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x1414,
	"Huawei E1414",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL, "0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x1416,
	"Huawei E1416",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL,  "0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x1417,
	"Huawei E1417",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB3", NULL,           NULL,           NULL,  "0","3",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x1418,
	"Huawei E1418",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL,  "0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x1419,
	"Huawei E1419",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL,  "0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x141A,
	"Huawei E141A",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL,  "0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x141B,
	"Huawei E141B",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB1", NULL,           NULL,           NULL,"0","1",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x141E,
	"Huawei E141E",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB1", NULL,           NULL,           NULL,  "0","1",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x1420,
	"Huawei E1420",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB1", NULL,           NULL,           NULL,  "0","1",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x1422,
	"Huawei E1422",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL, "0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x1427,
	"Huawei E1427",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB3", NULL,           NULL,           NULL,  "0","3",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x1428,
	"Huawei E1428",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB3", NULL,           NULL,           NULL, "0","3",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x1429,
	"Huawei E1429",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL,  "0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x142A,
	"Huawei E142A",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL, "0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x142B,
	"Huawei E142B",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB1", NULL,           NULL,           NULL,  "0","1",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x1433,
	"Huawei E1433",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB3", NULL,           NULL,           NULL,"0","3",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x1434,
	"Huawei E1434",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL,  "0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??                          dongle
{
	0x12D1, 0x1436,
	"Huawei E1436",
	RIL_MODEM_TYPE_USB_DONGLE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL, "0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x1438,
	"Huawei E1438",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL,"0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x1439,
	"Huawei E1439",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB3", NULL,           NULL,           NULL,"0","3",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x143A,
	"Huawei E143A",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL,"0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x143B,
	"Huawei E143B",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL,"0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x143E,
	"Huawei E143E",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL,"0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x143F,
	"Huawei E143F",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL,"0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x1448,
	"Huawei E1448",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB1", NULL,           NULL,           NULL,"0","1",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x144A,
	"Huawei E144A",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL,"0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x144B,
	"Huawei E144B",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB3", NULL,           NULL,           NULL,"0","3",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x144C,
	"Huawei E144C",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL,"0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x144D,
	"Huawei E144D",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB3", NULL,           NULL,           NULL,"0","3",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x1465,
	"Huawei K3765",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL,"0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei??
{
	0x12D1, 0x15FF,
	"Huawei E15FF",
	RIL_MODEM_TYPE_PCIE_MODULE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL,"0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA|RIL_MODEM_NETWORK_TYPE_CDMA|RIL_MODEM_NETWORK_TYPE_EVDO,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//Huawei E173s
{
	0x12D1, 0x1C05,
	"Huawei E173s",
	RIL_MODEM_TYPE_USB_DONGLE,
	"/dev/ttyUSB0", "/dev/ttyUSB2", NULL,           NULL,           NULL,"0","2",
	RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA,
	RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},


//ruisibo WH700G
{
        0x05c6, 0x6000,
        "WH700G",
        RIL_MODEM_TYPE_PCIE_MODULE,
        "/dev/ttyUSB0", "/dev/ttyUSB1", NULL,           NULL,           NULL,"0","1",
        RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA,
        RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//alcatel X220D
{
        0x1bbb, 0x0017,
        "alcatel X200",
        RIL_MODEM_TYPE_USB_DONGLE,
        "/dev/ttyUSB4", "/dev/ttyUSB3", NULL,           NULL,           NULL,"4","3",
        RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA,
        RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

//LINKTOP 
{
        0x230d, 0x000d,
        "LINKTOP 230D",
        RIL_MODEM_TYPE_USB_DONGLE,
        "/dev/ttyACM1", "/dev/ttyACM0", NULL,           NULL,           NULL,"1","0",
        RIL_MODEM_NETWORK_TYPE_GSM|RIL_MODEM_NETWORK_TYPE_WCDMA,
        RIL_SERVICE_TYPE_DATA_CALL|RIL_SERVICE_TYPE_SIM|RIL_SERVICE_TYPE_SMS|RIL_SERVICE_TYPE_NETWORK|RIL_SERVICE_TYPE_DEVICE
},

#endif
